set nocompatible

" Pathogen stuff
call pathogen#infect()
call pathogen#helptags()
call pathogen#runtime_append_all_bundles()

"
" from GOLANG vimrc stuff
"
filetype off
filetype plugin indent off
set runtimepath+=$GOROOT/misc/vim
filetype plugin indent on
syntax on

set number

set tabstop=2  
set autoindent
set copyindent
set shiftwidth=2
set shiftround
set smarttab

set showmatch
set ignorecase
set smartcase
set hlsearch 
set incsearch

set nobackup
set noswapfile

set backspace=indent,eol,start

set ttymouse=xterm2

colorscheme jellybeans
set t_Co=256


"
" Muh bindings!
"
let mapleader = ","

map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

nmap <Leader>w :w<CR>
nmap <Leader>n :noh<CR>

inoremap {<CR> {<CR>}<C-o>O

nmap <Leader>nt :NERDTree<CR>
