# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

#golang stuff
export PATH=$PATH:$HOME/Code/go/lang/bin
export GOPATH=$HOME/Code/go
export PATH=$PATH:$GOPATH/bin

export PATH="$PATH:/usr/local/mysql/bin"

export PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
export PATH=$PATH:/Applications/Postgres93.app/Contents/MacOS/bin/ #postgresql

export PATH=$PATH:/Users/rafy/Code/java/adt-bundle/sdk/platform-tools
export PATH=$PATH:/Users/rafy/Code/java/adt-bundle/sdk/tools

# MUH ALIASES

#function cd() {
#	builtin cd "$*" && ls
#}

function hist() {
  cat $HOME/.zsh_history | grep "$@"
}

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# use homebrew ctags
alias ctags="`brew --prefix`/bin/ctags"

[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh # This loads NVM

nvm use 0.10.26 > /dev/null
set -o vi

alias gitl="git log --all --graph --pretty=format:'%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"

alias gitclean='git branch --merged master | grep -v "\* master" | xargs -n 1 git branch -d'

alias server="python -m SimpleHTTPServer"
alias rg="cd ~/Documents/rangle"
